### ISSUE TITLE
[Feature Request] Implementation for Ubuntu Based distros

### ISSUE THREAD

**Issue by andr3slelouch** [andr3slelouch/Optimus-Manager-Indicator#20]
Hi @ViBE-HU, I have opened an issue to talk about ubuntu implementation here.

   The first question is how do you use prime-select in ubuntu? Just type "sudo prime-select nvidia" and you're done? or do you need to log out / login to see the changes? Because I can implement at least the logout which looks more like the behavior that optimus-manager has in arch linux.

**Comment by ViBE-HU** [comment]
I used prime-select command too but that was before I found GUI solutions. Nowadays I'm use this [plugin](https://extensions.gnome.org/extension/1275/prime-indicator/). But because it is not as informative like on Windows (cause no tray/shell indicator or integration) I try to find a working one for Ubuntu. I hardly ever used Arch so I don't know how it looks like.

**Comment by andr3slelouch** [comment]
I will look that extension and see how it is made, thanks

**Comment by andr3slelouch** [comment]
Hey @ViBE-HU can you try the recent version that i have uploaded? https://github.com/andr3slelouch/Optimus-Manager-Indicator/releases/tag/v2b2
Tell me if it works and if you detect some issues. Thanks in advance
